# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_mimicR_wrappers", use_symbols = TRUE, package_name = "mimicR")

#' @docType package
#' @usage NULL
#' @useDynLib mimicR, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' determine the depth(distance to root) of a term in the snomed hierarchy 
#' @export
get_depth <- function(relationship_file, terms) .Call(wrap__get_depth, relationship_file, terms)

#' Return string `"Hello world!"` to R.
#' @export
parse_mimic_noteevents <- function(file, tags, keep_rawtext, outfile, add_tags_to_bd) .Call(wrap__parse_mimic_noteevents, file, tags, keep_rawtext, outfile, add_tags_to_bd)

#'  Parse note-events files, extract discharge diagnosis free text, extract UMLS CUIs with metamap, map cuis to SNOMED
#' @export
get_freetext_diagnosis_as_snomed_ids <- function(noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, add_tags_to_bd) .Call(wrap__get_freetext_diagnosis_as_snomed_ids, noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, add_tags_to_bd)

#'  Parse note-events files, extract discharge diagnosis free text, extract UMLS CUIs with metamap, map cuis to SNOMED
#' @export
get_freetext_diagnosis_as_snomed_ids_filter_and_write <- function(noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, outfile, add_tags_to_bd) .Call(wrap__get_freetext_diagnosis_as_snomed_ids_filter_and_write, noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, outfile, add_tags_to_bd)

#'  Parse note-events files, extract discharge diagnosis free text, extract UMLS CUIs with metamap, map cuis to SNOMED
#' @export
get_freetext_diagnosis_forbatchmm <- function(noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, outfile, add_tags_to_bd) .Call(wrap__get_freetext_diagnosis_forbatchmm, noteevents_file, record_tags, umlsCUI_snomedID_mapfile, keep_types_list, outfile, add_tags_to_bd)

